// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0KwoUeBBGyG6QQI5HDeYOI2U_cG-sLok',
    appId: '1:242637986555:web:c5a31cc75e4db8212b2e5e',
    messagingSenderId: '242637986555',
    projectId: 'ekart-yellow',
    authDomain: 'ekart-yellow.firebaseapp.com',
    storageBucket: 'ekart-yellow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqbTzi7EKPii_m6Bwj6NuMigrfQ6FgRbo',
    appId: '1:242637986555:android:09ce48eec3f29c402b2e5e',
    messagingSenderId: '242637986555',
    projectId: 'ekart-yellow',
    storageBucket: 'ekart-yellow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAszREZvJ_j25P6mfa9-5qCZR3lhBbfCUY',
    appId: '1:242637986555:ios:249c85a58af12d142b2e5e',
    messagingSenderId: '242637986555',
    projectId: 'ekart-yellow',
    storageBucket: 'ekart-yellow.appspot.com',
    iosClientId: '242637986555-09gi5gnju67bqqi30be4b1o059aevlq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.yellowEkart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAszREZvJ_j25P6mfa9-5qCZR3lhBbfCUY',
    appId: '1:242637986555:ios:6b51bb8ec036c6f52b2e5e',
    messagingSenderId: '242637986555',
    projectId: 'ekart-yellow',
    storageBucket: 'ekart-yellow.appspot.com',
    iosClientId: '242637986555-1a39ii9smh1e67fib1ed953hias98hgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.yellowEkart.RunnerTests',
  );
}
